module FiscalYear
  class Half
    def self.first: () -> Array[Integer] | -> Array[untyped]
    def self.second: () -> Array[Integer] | -> Array[untyped]
    def self.first?: (Integer) -> bool
    def self.second?: (Integer) -> bool
    def self.months: (Integer) -> Array[Integer]
    def self.first_range_by: (Integer) -> Range[Date]
    def self.second_range_by: (Integer) -> Range[Date]
    def self.range_by: (Date) -> Range[Date]
    def self.cross_year_in_half?: (Array[Integer]) -> bool
    def self.passed_month_count_by: (Date) -> Integer
    def self.passed_month_count_by_month: (Integer) -> Integer
  end
end
